**************************************************************************************************************
Step 1: Create a Sample Table
-----------------------------
CREATE TABLE employees(
	id    SERIAL PRIMARY KEY,
	name  VARCHAR(100),
	department VARCHAR(50),
	salary    NUMERIC(10,2),
	hire_date DATE
);
-- Insert some sample data into the table
INSERT INTO employees(name,department,salary,hire_date) VALUES
('Alice','HR',50000,'2020-06-15'),
('Bob','Engineering',75000,'2019-03-22'),
('Charlie','Marketing',60000,'2021-08-10'),
('David','Engineering',80000,'2018-11-05'),
('Eve', 'HR', 55000, '2022-01-14'),
('Frank', 'Marketing', NULL, '2020-07-01');
**************************************************************************************************************

**************************************************************************************************************
Step 2: Filtering Examples
--------------------------
1. WHERE Clause
--The WHERE clause filters rows based on a specified condition.
--Example: Select employees from the "Engineering" department.
SELECT * FROM employees WHERE department = 'Engineering'


2. AND Operator
--The AND operator combines two boolean expressions and returns true if both expressions evaluate to true.
--Example: Select employees from the "Engineering" department who earn more than $70,000.
SELECT * FROM employees WHERE department = 'Engineering' AND salary >= 75000;


3. OR Operator
--The OR operator combines two boolean expressions and returns true if either expression evaluates to true.
--Example: Select employees from either the "HR" or "Marketing" departments.
SELECT * FROM employees WHERE department = 'HR' OR department = 'Marketing'

	
4. LIMIT Clause
--The LIMIT clause retrieves a subset of rows generated by a query.
--Example: Retrieve the first 3 employees from the table.
SELECT * FROM employees LIMIT 3
SELECT * FROM employees ORDER BY id DESC LIMIT 3


5. FETCH Clause
--The FETCH clause limits the number of rows returned by a query (similar to LIMIT).
--Example: Fetch the first 2 employees from the table.
SELECT * FROM employees FETCH FIRST 2 ROWS ONLY;


6. IN Operator
--The IN operator selects data that matches any value in a list of values.
--Example: Select employees from the "HR" or "Engineering" departments.
SELECT * FROM employees WHERE department IN ('HR','Marketing')


7. BETWEEN Operator
--The BETWEEN operator selects data that is within a range of values.
--Example: Select employees whose salary is between $50,000 and $70,000.
SELECT * FROM employees WHERE salary BETWEEN 50000 AND 70000

	
8. LIKE Operator
SELECT * FROM employees WHERE name LIKE 'A%'
SELECT * FROM employees WHERE name LIKE '%e'
SELECT * FROM employees WHERE name LIKE 'A____'
SELECT * FROM employees WHERE name ILIKE 'a%'
SELECT * FROM employees WHERE name LIKE '%e%'
SELECT * FROM employees WHERE name NOT LIKE 'A%'

	
9. IS NULL Operator
--The IS NULL operator checks if a value is NULL.
--Example: Select employees whose salary is NULL.
SELECT * FROM employees WHERE salary IS NULL
SELECT * FROM employees WHERE salary IS NOT  NULL

	
10. OFFSET
SELECT * FROM employees OFFSET 2 ROWS
SELECT * FROM employees OFFSET 2 ROWS LIMIT 2
SELECT * FROM employees OFFSET 2 ROWS FETCH FIRST 2 ROWS ONLY
**************************************************************************************************************
