Section 10. Transactions
PostgreSQL Transactions – show you how to handle transactions in PostgreSQL using BEGIN, COMMIT, and ROLLBACK statements.
******************************************************************************************************************
--01.TRANSACTION

--CREATE TABLE AND INSERT VALUES
DROP TABLE IF EXISTS accounts;

CREATE TABLE accounts (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    balance DEC(15,2) NOT NULL CHECK(balance >= 0),
    PRIMARY KEY(id)
);

--"INSERT WILL BE IMEDIATLY INSERT INTO THE TABLE IMPLICITY"
'For example, when you execute the following INSERT statement, PostgreSQL immediately inserts a new row into the accounts table:'
INSERT INTO accounts(name,balance)
	VALUES ('Tamizh',50000)

'IF YOU RUN THIS INSERT BEFORE THE BEGIN IT WILL EXPLICITY INSERT'
'NOW, U SELECT THE TABLE IN THIS SESSION YOU WILL SEE THE 2 RESULT
	BUT, ANOTHER SESSION ONLY ONE RESULT , SO, IF THE TRANSACTION
	WILL BE START WITH BEGIN THEN COMMIT THE CHANGES THEN ONLY UPDATE DABLE
	OTHERWISE NOT UPDATE'

--Begin a transaction
--When you execute a statement, PostgreSQL implicitly wraps it in a transaction.
--RUN BOTH BEGIN AND INSERT
BEGIN;

INSERT INTO accounts(name,balance)
VALUES('Thillai',10000);

	
SELECT * FROM accounts;
******************************************************************************************************************
--Commit a transaction
--To permanently apply the change to the database, you commit the transaction by using the COMMIT WORK statement:

-- start a transaction
BEGIN;
-- insert a new row into the accounts table
INSERT INTO accounts(name,balance)
VALUES('Alice',10000);
-- commit the change (or roll it back later)
COMMIT;
******************************************************************************************************************
--Roll back a transaction
'If you want to undo the changes to the database, you can use the ROLLBACK statement:'

-- start a transaction
BEGIN;
UPDATE accounts
SET balance = balance - 1000
WHERE id =  1;
-- rollback the changes
ROLLBACK;